version: '3'
services:
  #PHP Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend # php service container name
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: ttu_backend # php service name
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./laravel_project_directory_name/:/var/www # laravel_project_directory_name (replace your's)
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  #NGINX Service
  nginx:
    image: nginx:alpine
    container_name: tech_team_up_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./laravel_project_directory_name:/var/www # laravel_project_directory_name (replace your's)
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - app-network
  #MySql Service
  database:
    image: mysql:5.7
    container_name: mysql_database # Database service container name
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ttu_db # your database name
      MYSQL_ROOT_PASSWORD: secure_password # secure_password (replace with your's) --> mysql root password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/data
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
